includes:
  - configs/s2ef/2M/equiformer_v2/base_distill.yml
trainer: distill
distillation:
  distill_loss: node2node_distill_loss 
  distill_lambda: 10000.0

model:
  use_distill: True
  teacher_node_dim: 128
  teacher_edge_dim: 128
