includes:
  - configs/s2ef/200k/painn/painn_base_distill_eqv2.yml
trainer: distill
distillation:
  distill_loss: node2node_distill_loss,edge2node_distill_loss,vec2vec_distill_loss 
  distill_lambda: [100.0, 0.05, 1.0]

model:
  use_distill: True
  teacher_node_dim: 128
  teacher_edge_dim: 512
