includes:
  - configs/s2ef/2M/painn/eqv2-painn-kd/painn_base_distill_eqv2.yml
trainer: distill
distillation:
  distill_loss: node2node_distill_loss 
  distill_lambda: 10000.0

model:
  use_distill: True
  teacher_node_dim: 128
  teacher_edge_dim: 512
